<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXiQeQQc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXiQeQQc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXiQeQQc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXiQeQQc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXiQeQQc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XiQeQQc',
    'container.build_id' => 'f45fdb25',
    'container.build_time' => 1587289445,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXiQeQQc');
