<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHmiMe90\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHmiMe90/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHmiMe90.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHmiMe90\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHmiMe90\App_KernelDevDebugContainer([
    'container.build_hash' => 'HmiMe90',
    'container.build_id' => 'b819537a',
    'container.build_time' => 1587140864,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHmiMe90');
